travis:
  secure:
    BINSTAR_TOKEN: gZWOLrvm9mI50BdwTPPF4gds0Rua8LiGKTveVflajDFI/8uCdkWYFF9OzBGd9vQjGeZF43AcYcyBXyjjPMAx5cM1l3dSEATcHKPcpM/OtV/yVUrMieDudGDIm9cpTLKj0tzawpT5RsNTFtiriw8gILE5hX51Bc/U88YszA/oMHk9rzX72nhrdEK/EdNtc+ArOG6tfI54YyUnoy4/QC6WCYl6c8rddpFMVheJ8V727/30pt+DjOAh9hD7NNNRNjpmbhLlCbC4sfNQ9eWaYugXdPacJahTaNdHYToKsPApohGz+tg5h3ArZK8OceTCbNYIHS91uz4ASJ4bhIMCmfKSPXz8qvK53DZWJJ9NYEneYuiMbf9Eqv/1Z4+1mzqXl/QSHKR9dTETLsVUaa7gBYvRTQp2ZZru+fgkwBtm0rk1/MFxA/FfMEwG7MhJm8SUpShZjz/HH1hOvHuB9+EXWzhEy2Nevf9Cy9q2JADVQjoqqk+kd+p7o0FaV3Lr2006jHEZNYUVE/muZ39ahUWtfnnr/uRJvE/3Vu8SBsLUqVMCHke7lk9qkIFK5Zy1bjdgY4sg31KXYwQv4mcatrde73LQE0DqTP3ct5fGzJtO0yqbgG8zu5dpf3pnWYkT8Fw4yQAc3rV8FuCbW+SxHSBIlojxzbgXahQIpO0lOUiOELpFQmw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
