travis:
  secure:
    BINSTAR_TOKEN: aTtkb71WMHKDSdx+2pAZ8fC8p60TTujJl2bETSa5C3f6uuxdqOBhOxvqYGZa+z5RwxCCClVngGXUZRD9zc1X8bKiP+1GOlSEtsacdHADkcvteycOZJMAC+odhFJAvv2zimGYvIPKk1vf1tkrOR+XIAxBClBzXybmreGKMrbZ7DrigLSID7sFWsJKu4W4RMYWIfiHx6d/slGGkkoSUF6ONjm/2zUPnUwe7YTJIOLDDXjdGiNlQgMo5+4UBL+/lJBhLAR82oeU0YZN26I22+KdF2DCN7UVeLN8pW1PVh4a/jZHBQrQmOOhGZ4nK4EyVUTmXoecSUrdLSnT3+ywF1bVpz4y8qiIVodxvHDyq+4dMCviVrdUrbK2bYKFm5ikPKYLs+ewXw4Zdvb7GwC5dNIADoRz0W39n8okg5IO+1xB9daW2tbZS10/i6RWNUqqk5i+dSi9URWV7Y8DljXWtxVpIuFvAknWmqXr57m58NV/RmaQcSC28HjaYhv7Mdhtp78XROq4cVGSzef2WD6cSsaOrkrIA4r4OT7g/6adHiN/7qSK6rGLwbrw5vBWtATqWEmC977kHfIKKzwcMDkPLbl6kls6loiUPreO3ubTctu/omi3O9A87FI6lJWINa2hdq8cLeJCGuc+nBT92eFM2wjvHF4iVK7zy3bMPGUZ6BV3Mdo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
